config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  resources :investments
  resources :jobs
  resources :companies
  get 'pages/home'
  get 'sessions/new'
  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/investment.rb
class Investment < ApplicationRecord
  has_one :user
  has_one :company

  def self.status_options
    %w(interest invited deck associate partner partners dd terms docs wired)
  end

  validates :status, inclusion: { in: self.status_options}
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: %i[ show edit update destroy ]
  before_action :set_status_options, only: %i[ new edit ]

  # GET /investments or /investments.json
  def index
    @investments = Investment.all
  end

  # GET /investments/1 or /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments or /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to investment_url(@investment), notice: "Investment was successfully created." }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1 or /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to investment_url(@investment), notice: "Investment was successfully updated." }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1 or /investments/1.json
  def destroy
    @investment.destroy

    respond_to do |format|
      format.html { redirect_to investments_url, notice: "Investment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    def set_status_options
      @status_options = Investment.status_options
    end

    # Only allow a list of trusted parameters through.
    def investment_params
      params.require(:investment).permit(:user_id, :company_id, :amount, :status)
    end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_with(model: investment) do |form| %>
  <% if investment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
        <% investment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :company_id, style: "display: block" %>
    <%= form.number_field :company_id %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, @status_options %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/investments/_investment.html.erb
<div id="<%= dom_id investment %>">
  <p>
    <strong>User:</strong>
    <%= investment.user_id %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= investment.company_id %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= investment.amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= investment.status %>
  </p>

</div>

app/views/investments/edit.html.erb
<h1>Editing investment</h1>

<%= render "form", investment: @investment %>

<br>

<div>
  <%= link_to "Show this investment", @investment %> |
  <%= link_to "Back to investments", investments_path %>
</div>

app/views/investments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Investments</h1>

<div id="investments">
  <% @investments.each do |investment| %>
    <%= render investment %>
    <p>
      <%= link_to "Show this investment", investment %>
    </p>
  <% end %>
</div>

<%= link_to "New investment", new_investment_path %>

app/views/investments/new.html.erb
<h1>New investment</h1>

<%= render "form", investment: @investment %>

<br>

<div>
  <%= link_to "Back to investments", investments_path %>
</div>

app/views/investments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @investment %>

<div>
  <%= link_to "Edit this investment", edit_investment_path(@investment) %> |
  <%= link_to "Back to investments", investments_path %>

  <%= button_to "Destroy this investment", @investment, method: :delete %>
</div>