config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  resources :investments
  resources :jobs
  resources :companies
  get 'pages/home'
  get 'sessions/new'
  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/job.rb
class Job < ApplicationRecord
  has_one :user
  has_one :company
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:user_id, :company_id, :start, :end, :title)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :company_id, style: "display: block" %>
    <%= form.number_field :company_id %>
  </div>

  <div>
    <%= form.label :start, style: "display: block" %>
    <%= form.date_field :start %>
  </div>

  <div>
    <%= form.label :end, style: "display: block" %>
    <%= form.date_field :end %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>User:</strong>
    <%= job.user_id %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= job.company_id %>
  </p>

  <p>
    <strong>Start:</strong>
    <%= job.start %>
  </p>

  <p>
    <strong>End:</strong>
    <%= job.end %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= job.title %>
  </p>

</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>

<div id="jobs">
  <% @jobs.each do |job| %>
    <%= render job %>
    <p>
      <%= link_to "Show this job", job %>
    </p>
  <% end %>
</div>

<%= link_to "New job", new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>