config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  resources :investments
  resources :jobs
  resources :companies
  get 'pages/home'
  get 'sessions/new'
  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/objective.rb
class Objective < ApplicationRecord
  has_one :company

  def self.metric_options
    %w(views contributors installations arr)
  end

  validates :metric, inclusion: { in: self.metric_options }
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: %i[ show edit update destroy ]
  before_action :set_metric_options, only: %i[ new edit ]

  # GET /objectives or /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1 or /objectives/1.json
  def show
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives or /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to objective_url(@objective), notice: "Objective was successfully created." }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1 or /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to objective_url(@objective), notice: "Objective was successfully updated." }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1 or /objectives/1.json
  def destroy
    @objective.destroy

    respond_to do |format|
      format.html { redirect_to objectives_url, notice: "Objective was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    def set_metric_options
      @metric_options = Objective.metric_options
    end

    # Only allow a list of trusted parameters through.
    def objective_params
      params.require(:objective).permit(:end, :metric, :goal, :result)
    end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<%= form_with(model: objective) do |form| %>
  <% if objective.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
        <% objective.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :end, style: "display: block" %>
    <%= form.date_field :end %>
  </div>

  <div>
    <%= form.label :metric, style: "display: block" %>
    <%= form.select :metric, @metric_options %>
  </div>

  <div>
    <%= form.label :goal, style: "display: block" %>
    <%= form.number_field :goal %>
  </div>

  <div>
    <%= form.label :result, style: "display: block" %>
    <%= form.number_field :result %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/objectives/_objective.html.erb
<div id="<%= dom_id objective %>">
  <p>
    <strong>End:</strong>
    <%= objective.end %>
  </p>

  <p>
    <strong>Metric:</strong>
    <%= objective.metric %>
  </p>

  <p>
    <strong>Goal:</strong>
    <%= objective.goal %>
  </p>

  <p>
    <strong>Result:</strong>
    <%= objective.result %>
  </p>

</div>

app/views/objectives/edit.html.erb
<h1>Editing objective</h1>

<%= render "form", objective: @objective %>

<br>

<div>
  <%= link_to "Show this objective", @objective %> |
  <%= link_to "Back to objectives", objectives_path %>
</div>

app/views/objectives/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Objectives</h1>

<div id="objectives">
  <% @objectives.each do |objective| %>
    <%= render objective %>
    <p>
      <%= link_to "Show this objective", objective %>
    </p>
  <% end %>
</div>

<%= link_to "New objective", new_objective_path %>

app/views/objectives/new.html.erb
<h1>New objective</h1>

<%= render "form", objective: @objective %>

<br>

<div>
  <%= link_to "Back to objectives", objectives_path %>
</div>

app/views/objectives/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @objective %>

<div>
  <%= link_to "Edit this objective", edit_objective_path(@objective) %> |
  <%= link_to "Back to objectives", objectives_path %>

  <%= button_to "Destroy this objective", @objective, method: :delete %>
</div>