config/routes.rb
Rails.application.routes.draw do
  resources :objectives
  resources :investments
  resources :jobs
  resources :companies
  get 'pages/home'
  get 'sessions/new'
  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
  has_many :investments
  has_many :objectives
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :metric)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :metric, style: "display: block" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Companies</h1>

<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
    <p>
      <%= link_to "Show this company", company %>
    </p>
  <% end %>
</div>

<%= link_to "New company", new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Back to companies", companies_path %>

  <%= button_to "Destroy this company", @company, method: :delete %>
</div>